<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Countdown to Our Wedding</title>
    <style>
        /* CSS untuk desain dan background */
        body {
            margin: 0;
            padding: 0;
            font-family: 'Arial', sans-serif;
            color: #fff;
            text-align: center;
            background: url('https://i.pinimg.com/736x/34/7a/ae/347aae2e5676309c81e26da3abaf398d.jpg') no-repeat center center/cover;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
        }

        .container {
            background: rgba(0, 0, 0, 0.7);
            padding: 20px 30px;
            border-radius: 15px;
            box-shadow: 0 8px 15px rgba(0, 0, 0, 0.5);
            position: relative;
            top: 2%; /* Geser sedikit lebih atas */
            animation: fadeIn 2s ease-in-out;
        }

        h1, h2 {
            margin: 0;
            padding: 10px 0;
        }

        h1 {
            font-size: 2.5rem;
            font-weight: bold;
        }

        h2 {
            font-size: 1.2rem;
            font-weight: lighter;
        }

        /* Teks Arab di atas Countdown */
        .arabic-text {
            font-size: 1.5rem;
            font-weight: bold;
            margin-bottom: 30px; /* Memberi ruang lebih banyak antara teks arab dan countdown */
        }

        .countdown {
            display: flex;
            justify-content: center;
            gap: 15px;
            margin-top: 20px; /* Memberi ruang tambahan untuk Countdown */
        }

        .time {
            background: #fbb034;
            padding: 15px 20px;
            border-radius: 10px;
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .time span {
            display: block;
            font-size: 2rem;
            font-weight: bold;
        }

        .time label {
            font-size: 1rem;
            font-weight: lighter;
        }

        /* Foto dengan efek transparansi bertahap di sekelilingnya */
        .photo-left, .photo-right {
            position: absolute;
            top: 0; /* Posisi atas foto */
            width: 150px;
            height: 300px;
            border-radius: 10px;
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            object-fit: cover;
            object-position: 0 -5cm; /* Crop bagian atas foto sekitar 5cm */
            animation: fadeIn 2s ease-in-out;
        }

        .photo-left {
            left: 10px;
            background-image: 
                linear-gradient(to right, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 0) 50%), /* Gradiasi kiri */
                linear-gradient(to bottom, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 0) 50%), /* Gradiasi bawah */
                linear-gradient(to left, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 0) 50%), /* Gradiasi kanan */
                linear-gradient(to top, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 0) 50%), /* Gradiasi atas */
                url('https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj3DGwO0cmxtW8NkrxGCRXS4ho5Jm4zcxr2wA6D9wzCgyoqf33uSF5YZq2qHN1F2xUaHwlWq7baPD6g3Wh-CxBwPasxleqh-_gp6mQfO9QLcMxlPdHoUWNZe8BDFeJB6v18R5DthT65VlE5AIKeg_jIP_qh0qvBiatacEXJF5Z08Z6INsm9wfqh85Peob-b/s586/WhatsApp%20Image%202024-11-29%20at%2017.40.56-removebg-preview.jpg');
        }

        .photo-right {
            right: 10px;
            background-image: 
                linear-gradient(to left, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 0) 50%), /* Gradiasi kanan */
                linear-gradient(to bottom, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 0) 50%), /* Gradiasi bawah */
                linear-gradient(to right, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 0) 50%), /* Gradiasi kiri */
                linear-gradient(to top, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 0) 50%), /* Gradiasi atas */
                url('https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgXe6my22zOoQaxTMHr-xHr9kfBqID8jGy6swqlaXIr0-Pl5aOi18ERs1aFovcXxKvC9-Fz9n1UM0viVRodfrCwC3bRQUD4Q5KGBHIfscmkeSckFnwX-yzkr0k-unqaFYmU3bdoRADDhsMeSx7wOgphg7klrYOElVOWhgoOffdln3e6ung_n_d6tMrl3ocN/s587/WhatsApp%20Image%202024-11-29%20at%2017.18.32-removebg-preview.jpg');
        }

        footer {
            margin-top: 20px;
            font-size: 0.9rem;
            color: #ccc;
        }

        /* Animasi fadeIn */
        @keyframes fadeIn {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <!-- Teks Arab di atas Countdown -->
        <div class="arabic-text">بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ</div>
        
        <h1>Countdown to Our Wedding</h1>
        <h2>Muhammad Sagise Ainun Naim & Naviatul Hasanah</h2>
        
        <!-- Foto Anda dan pasangan menggunakan tag img -->
        <div class="photo-left"></div>
        <div class="photo-right"></div>
        
        <div class="countdown">
            <div class="time">
                <span id="days">0</span>
                <label>Days</label>
            </div>
            <div class="time">
                <span id="hours">0</span>
                <label>Hours</label>
            </div>
            <div class="time">
                <span id="minutes">0</span>
                <label>Minutes</label>
            </div>
            <div class="time">
                <span id="seconds">0</span>
                <label>Seconds</label>
            </div>
        </div>
        <footer>
            <p>Mark the date: 25 January 2025 at 10:01 AM WIB</p>
        </footer>
    </div>

    <script>
        const weddingDate = new Date('2025-01-25T03:01:00Z'); // UTC untuk 10:01 WIB

        function updateCountdown() {
            const now = new Date();
            const timeRemaining = weddingDate - now;

            const days = Math.floor(timeRemaining / (1000 * 60 * 60 * 24));
            const hours = Math.floor((timeRemaining % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            const minutes = Math.floor((timeRemaining % (1000 * 60 * 60)) / (1000 * 60));
            const seconds = Math.floor((timeRemaining % (1000 * 60)) / 1000);

            document.getElementById('days').innerText = days;
            document.getElementById('hours').innerText = hours;
            document.getElementById('minutes').innerText = minutes;
            document.getElementById('seconds').innerText = seconds;
        }

        setInterval(updateCountdown, 1000);
        updateCountdown();
    </script>
</body>
</html>
